version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - my-services
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./configs:/etc/nginx/conf.d"

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cloud
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    volumes:
      - './cloud-mysql:/var/lib/mysql'
    networks:
      - my-services
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.0.4
    networks:
      - my-services
    environment:
      VIRTUAL_HOST: phpmyadmin.localhost
      VIRTUAL_PORT: 80
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 2G
    depends_on:
      - mysql
    restart: always

networks:
  my-services:
    external: true
volumes:
  mysql:
    driver: local